name: Auto Label PR

on:
  pull_request:
    types:
      - opened

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs-review
